pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
		stage('Upload jar to Nexus'){
			steps {
				nexusArtifactUploader artifacts: [
				[
				artifactId: 'my-app', 
				classifier: '', 
				file: 'target/my-app-1.0-SNAPSHOT.jar',
				type: 'jar'
				]
			  ], 
				credentialsId: 'nexus-credentials',
				groupId: 'com.mycompany.app',
				nexusUrl: '192.168.22.119:8081',
				nexusVersion: 'nexus3',
				protocol: 'http', 
				repository: 'simple-java-maven-app', 
				version: '1.0-SNAPSHOT'
			}
		}
    }
}
